# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord', '~> 7.1'
gem 'activestorage', '~> 7.1'
gem 'aws-sdk-s3', '~> 1.170', require: false
gem 'base64', '~> 0.2.0'
gem 'bcrypt'
gem 'image_processing', '~> 1.13'
gem 'connection_pool', '~> 2.5'
gem 'dotenv'
gem 'faraday'
gem 'faye-websocket'
gem 'json', '~> 2.10'
gem 'mail'
gem 'openssl', '~> 3.3'
gem 'pg'
gem 'puma'
gem 'rack'
gem 'rack-test'
gem 'rackup'
gem 'rake'
gem 'redis'
gem 'rspec'
gem 'securerandom', '~> 0.4.1'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'twilio-ruby'

group :development do
  gem 'faker'
  gem 'pry'
  gem 'rubocop', require: false
  gem 'ruby-progressbar'
end
